### ISSUE TITLE
SNP to RE file

### ISSUE THREAD

**Issue by jelman** [sldrcyang/T-MAGMA#3]
Hello,

Congratulations on a very interesting paper! I would like to apply this approach, but was wondering what file you used for RELOC.txt in order to create the snp_to_re annotation?

Thank you for your help,
Jeremy

**Comment by sldrcyang** [comment]
Hello,

Thanks for your interest in our project. We have uploaded the files in the RELOC folder, and the illustration is written in the Main_script.txt. I hope it's useful for you.

Good luck,
Anyi Yang

**Comment by jelman** [comment]
This is excellent, thank you very much!

Jeremy
